version: "1.0"
info:
  model: int-scaffold
packages:
- name: GitProjectTestNewProject
  gitServerName: SanthoshK
  gitUrl: https://github.com/santhu736852
  gitUsername: santhu736852
  gitBranch: main
services:
- serviceName: project.gitprojecttestnew.integrations:new1
  packages:
  - name: GitProjectTestNewProject
    version: "1.0"
- serviceName: pub.date:calculateDateDifference
  packages:
  - name: WmPublic
    version: 11.1.0.0.2004
